---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: yarn-install
  pull: always
  image: node:latest
  commands:
  - pwd
  - yarn install

- name: lint test
  pull: always
  image: node:latest
  commands:
  - yarn lint

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**

---
kind: pipeline
type: docker
name: unit-tests

platform:
  os: linux
  arch: amd64

steps:
- name: yarn-install
  pull: always
  image: node:latest
  commands:
  - pwd
  - yarn install

- name: unit-tests
  pull: always
  image: node:latest
  commands:
  - yarn test

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**

---
kind: pipeline
type: docker
name: integration-tests

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: owncloud-test-middleware

steps:
- name: yarn-install
  pull: always
  image: node:latest
  commands:
  - pwd
  - yarn install

- name: install-core
  pull: always
  image: owncloudci/core
  commands:
  - ls
  - . /var/www/owncloud/owncloud-test-middleware/.drone.env
  - export PLUGIN_GIT_REFERENCE=$CORE_COMMITID
  - bash /usr/sbin/plugin.sh
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud

- name: owncloud-log
  pull: always
  image: owncloud/ubuntu:16.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.4
  commands:
  - ls /var/www/owncloud/
  - ls /var/www/owncloud/server
  - cd /var/www/owncloud/server
  - chown www-data * -R

- name: integration-tests
  pull: always
  image: node:latest
  commands:
  - pwd
  - cd /var/www/owncloud/owncloud-test-middleware
  - jest tests
  environment:
    BACKEND_HOST: http://owncloud
    CORE_PATH: /var/www/owncloud/server

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: owncloud
  pull: always
  image: owncloudci/php:7.4
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server/

volumes:
- name: uploads
  temp: {}
- name: configs
  temp: {}

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**

...
